project_id = "mnnasokmyyvshroujipp"

[functions.generate-outfit]
verify_jwt = false

[functions.seed-test-clothing]
verify_jwt = false

[functions.upgrade-outfit]
verify_jwt = false

[functions.auth-proxy]
verify_jwt = false

[functions.seed-inspiration]
verify_jwt = false
